"""Give every build its own version: increase ``build`` in ``version.json`` and write the
Windows version resource ``build/version_info.txt`` used by ``PhotoBatchEditor.spec``.

Run by ``build_windows.bat`` / ``build_mac.sh`` before PyInstaller. Prints the new version
(``1.0.0.12``). ``--print`` only prints the current version (``build_installer.bat``).

    python tools/bump_build.py            # 1.0.0.11 -> 1.0.0.12
    python tools/bump_build.py --print    # 1.0.0.12

A release version (``X.Y.Z``) is changed by hand in ``version.json``.
"""

from __future__ import annotations

import sys
from dataclasses import replace
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from core.version import VERSION_FILE, AppVersion, read_version, write_version  # noqa: E402

VERSION_INFO = ROOT / 'build' / 'version_info.txt'

# PyInstaller "--version-file" format (VSVersionInfo): Explorer > Properties > Details shows it.
# A real version resource makes the .exe look less like a bare packed script to antivirus heuristics.
TEMPLATE = """# UTF-8 — generated by tools/bump_build.py, do not edit
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={nums},
    prodvers={nums},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'Photo Batch Editor'),
        StringStruct('FileDescription', 'Photo Batch Editor'),
        StringStruct('FileVersion', '{full}'),
        StringStruct('InternalName', 'PhotoBatchEditor'),
        StringStruct('LegalCopyright', 'Copyright (c) Photo Batch Editor'),
        StringStruct('OriginalFilename', 'PhotoBatchEditor.exe'),
        StringStruct('ProductName', 'Photo Batch Editor'),
        StringStruct('ProductVersion', '{full}')
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def write_version_info(ver: AppVersion, path: Path = VERSION_INFO) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(TEMPLATE.format(nums=ver.numbers, full=ver.full), encoding='utf-8')


def main(argv: list[str]) -> int:
    file = ROOT / VERSION_FILE
    ver = read_version(file)
    if '--print' not in argv:
        ver = replace(ver, build=ver.build + 1)
        write_version(file, ver)
        write_version_info(ver)
    print(ver.full)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
